### ISSUE TITLE
Mocking __getitem__ on Pusher

### ISSUE THREAD

**Issue by sivy** [pusher/pusher-http-python#10]
I'm working on stubbing two parts of the Pusher API so that my unit tests don't actually shove data down the pipe, and so that I can confirm that Pusher is being called with the right data during various operations.

I'm using unittest2 and Mock (<http://www.voidspace.org.uk/python/mock/>):

```python
    # spec'd the namespaced version where it's been imported - seems to be a requirement for Mock
    # use MagicMock which also mocks all the magic (__underscored__) methods for the class
    self.mock_pusher = MagicMock(
    spec=myapp.feature.pusher.Pusher,
            autospec=True)
```

As a debug help, I edited `pusher/__init__.py` to let me know when Pusher.\_\_getitem__ has been called.

In my test code:
```python
    class BasicTestCase(TestCase):
        def setUp(self):
            self.channel_name = 'foo'
            self.mock_pusher = MagicMock(
                    spec=myapp.somemodule.pusher.Pusher,
                    autospec=True)

        def test(self):
            self.do_task_that_gets_a_pusher_channel()
            self.mock_pusher.__getitem__.assert_any_call(
                    self.channel_name)
```

When I run the tests:

```
./manage.py test -v2 myapp.BasicTestCase

test (myapp.tests.BasicTestCase) ... __getitem__: client-foo
FAIL
...
...
======================================================================
FAIL: test (myapp.tests.BasicTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/steve/PROJECTS/myapp/tests/feature.py", line 257, in test
    self.channel_name)
  File "/Users/steve/envs/myapp/lib/python2.7/site-packages/mock.py", line 820, in assert_called_with
    raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: __getitem__('client-foo')
Not called

```

I've also tried Mocking `pusher.Pusher` instead of the namespaced version, but it doesn't seem to affect the issue.

Thoughts?

**Comment by zimbatm** [comment]
1.0 should be much easier to mock. A custom backend could be provided that simulates HTTP requests and responses accordingly.
