### ISSUE TITLE
Traceback (PusherBadStatus: 599) under heavy load in Tornado library

### ISSUE THREAD

**Issue by michaelperret** [pusher/pusher-http-python#118]
Any ideas as to what may be the root cause here? We aren't seeing any other error logs or issues and this traceback isn't super informative

```
Exception in callback <function process_response_future at 0x7fd1092058c0> for <tornado.concurrent.Future object at 0x7fd1094c4410>
Traceback (most recent call last):
  File "/opt/core/current/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 317, in _set_done
    cb(self)
  File "/opt/core/current/env/local/lib/python2.7/site-packages/pusher/tornado.py", line 46, in process_response_future
    future.set_result(process_response(code, body))
  File "/opt/core/current/env/local/lib/python2.7/site-packages/pusher/http.py", line 65, in process_response
    raise PusherBadStatus("%s: %s" % (status, body))
PusherBadStatus: 599:
```

env: Python 2.7, Tornado 4.3, Pusher 1.7.4

**Comment by WillSewell** [comment]
This means you received an HTTP error code https://httpstatuses.com/599. Are your requests going through a forward proxy by any chance?

**Comment by WillSewell** [comment]
For the record, we believe this is due to an underlying issue in the tornado library: https://github.com/tornadoweb/tornado/issues/1753
