### ISSUE TITLE
Pusher 2.1.0 is missing `pynacl` dependency

### ISSUE THREAD

**Issue by TheKevJames** [pusher/pusher-http-python#128]
The latest release pushed to PyPI seems to be throwing errors on import. I assume [pynacl](https://github.com/pyca/pynacl) should be added to the project dependencies:

```
» python3 -m venv /tmp/venv
» source /tmp/venv/bin/activate
(venv) » pip install pusher==2.1.0 
# output snipped ...
(venv) » python
Python 3.7.1 (default, Nov  6 2018, 18:49:54)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
>>> import pusher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.7/site-packages/pusher/__init__.py", line 3, in <module>
    from .pusher import Pusher
  File "/private/tmp/venv/lib/python3.7/site-packages/pusher/pusher.py", line 21, in <module>
    from pusher.pusher_client import PusherClient
  File "/private/tmp/venv/lib/python3.7/site-packages/pusher/pusher_client.py", line 27, in <module>
    from pusher.crypto import *
  File "/private/tmp/venv/lib/python3.7/site-packages/pusher/crypto.py", line 10, in <module>
    import nacl
ModuleNotFoundError: No module named 'nacl'
>>>
```

/cc @damdo and @WillSewell

**Comment by damdo** [comment]
Thank you for reporting this problem, we fixed that and released a new version. To ensure you get the latest version you can install it via: `pip install --no-cache-dir pusher`

**Comment by ConfidenceYobo** [comment]
I am also having this issue with pusher v3.1.0
