### ISSUE TITLE
pip openssl error

### ISSUE THREAD

**Issue by tulpn** [pusher/pusher-http-python#68]
Hi everyone, 

I have just installed pusher via pip and it seems that it brakes my pip. From what I have understood is that is a concern between openssl urllib3 and requests. 

However, I am not sure how to fix it. 

Here my console output.
```
(myproject)bs@debian-gohan:/var/www/vhosts/api-example.com/api$ pip install pusher
Downloading/unpacking pusher
  Downloading pusher-1.2.3-py2.py3-none-any.whl (156kB): 156kB downloaded
Downloading/unpacking pyasn1 (from pusher)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Downloading/unpacking ndg-httpsclient (from pusher)
  Downloading ndg_httpsclient-0.4.0.tar.gz
  Running setup.py (path:/home/envs/myproject/build/ndg-httpsclient/setup.py) egg_info for package ndg-httpsclient
    
Downloading/unpacking pyopenssl (from pusher)
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB): 102kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six in /home/envs/myproject/lib/python2.7/site-packages (from pusher)
Downloading/unpacking urllib3 (from pusher)
  Downloading urllib3-1.14-py2.py3-none-any.whl (89kB): 89kB downloaded
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /home/envs/myproject/lib/python2.7/site-packages (from pusher)
Downloading/unpacking cryptography>=0.7 (from pyopenssl->pusher)
  Downloading cryptography-1.2.1.tar.gz (372kB): 372kB downloaded
  Running setup.py (path:/home/envs/myproject/build/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking idna>=2.0 (from cryptography>=0.7->pyopenssl->pusher)
  Downloading idna-2.0-py2.py3-none-any.whl (61kB): 61kB downloaded
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /home/envs/myproject/lib/python2.7/site-packages (from cryptography>=0.7->pyopenssl->pusher)
Downloading/unpacking enum34 (from cryptography>=0.7->pyopenssl->pusher)
  Downloading enum34-1.1.2.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/home/envs/myproject/build/enum34/setup.py) egg_info for package enum34
    
Downloading/unpacking ipaddress (from cryptography>=0.7->pyopenssl->pusher)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=0.7->pyopenssl->pusher)
  Downloading cffi-1.5.0.tar.gz (385kB): 385kB downloaded
  Running setup.py (path:/home/envs/myproject/build/cffi/setup.py) egg_info for package cffi
    
Downloading/unpacking pycparser (from cffi>=1.4.1->cryptography>=0.7->pyopenssl->pusher)
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/home/envs/myproject/build/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: pusher, pyasn1, ndg-httpsclient, pyopenssl, urllib3, cryptography, idna, enum34, ipaddress, cffi, pycparser
Compiling /home/envs/myproject/build/pusher/pusher/aiohttp.py ...
  File "/home/envs/myproject/build/pusher/pusher/aiohttp.py", line 24
    response = yield from asyncio.wait_for(
                        ^
SyntaxError: invalid syntax

  Running setup.py install for ndg-httpsclient
    Skipping installation of /home/envs/myproject/lib/python2.7/site-packages/ndg/__init__.py (namespace package)
    
    Installing /home/envs/myproject/lib/python2.7/site-packages/ndg_httpsclient-0.4.0-py2.7-nspkg.pth
    Installing ndg_httpclient script to /home/envs/myproject/bin
  Running setup.py install for cryptography
    
    Installed /home/envs/myproject/build/cryptography/cffi-1.5.0-py2.7-linux-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.14
    Downloading https://pypi.python.org/packages/source/p/pycparser/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935
    Processing pycparser-2.14.tar.gz
    Writing /tmp/easy_install-W85lQP/pycparser-2.14/setup.cfg
    Running pycparser-2.14/setup.py -q bdist_egg --dist-dir /tmp/easy_install-W85lQP/pycparser-2.14/egg-dist-tmp-w21X7P
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    
    Installed /home/envs/myproject/build/cryptography/pycparser-2.14-py2.7.egg
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o -lssl -lcrypto -o build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/_openssl.so
    building '_constant_time' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_constant_time.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_constant_time.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_constant_time.o -o build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/_constant_time.so
    building '_padding' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_padding.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_padding.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_padding.o -o build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/_padding.so
  Running setup.py install for enum34
    
  Running setup.py install for cffi
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-2.7/_cffi_backend.so
    
  Running setup.py install for pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    Build the lexing/parsing tables
Successfully installed pusher pyasn1 ndg-httpsclient pyopenssl urllib3 cryptography idna enum34 ipaddress cffi pycparser
Cleaning up...
```

Which leaves me with:
```
(myproject)bs@debian-gohan:/var/www/vhosts/api-example.com/api$ pip
Traceback (most recent call last):
  File "/home/bs/envs/myproject/bin/pip", line 7, in <module>
    from pip import main
  File "/home/bs/envs/myproject/local/lib/python2.7/site-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/bs/envs/myproject/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/bs/envs/myproject/local/lib/python2.7/site-packages/pip/download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "/home/bs/envs/myproject/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/bs/envs/myproject/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

I am using Python 2.7. The project I am working with is a Django project and all code with Pusher was executed fine. But since pip is broke I cannot freeze and push to staging env. Not quite sure how to tell you the pip version.

I know this might not exactly belong here as it is not directly related to pusher, but I thought I let you know that the requirements of pusher cause this issue! I will investigate and post updates for other users...

**Comment by tulpn** [comment]
Not quite sure, what happened. But I deleted my virtualenv, created a new one. Installed urllib3 then openssl and then the others and lastly pusher. Everything worked fine!

**Comment by zimbatm** [comment]
Good that you figured it out. SSL has always been a big source of errors for me in various languages. Maybe OpenSSL got an upgrade and it couldn't dynamically link the library anymore (and thus inject the right constants).
